[tool.poetry]
name = "python-my-package"
version = "0.1.0"
description = ""
authors = ["mi11km <mi11km.program@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
