[tool.poetry]
name = "python-my-package"
version = "0.1.0"
description = ""
authors = ["mi11km <mi11km.program@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9.7"
numpy = "^1.21.2"
matplotlib = "^3.4.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
